Home work 18
UnitOmega13/HomeWork pull request #22
Opened 2019-07-01 21:37 UTC by UnitOmega13

2019-07-04 08:40 UTC, SevostyanovGerman requested changes

2019-07-04 08:40 UTC, SevostyanovGerman commented on src/main/java/main/Main.java
> +            e.printStackTrace();
check last work in your group, u have the same problems

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/AccountService.java
> +        System.out.println("AccountService loaded");
do we need sout here?

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/DataBaseService.java
> +    private static final String hibernate_hbm2ddl_auto = "update"; // create
to we need this comment?

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/DataBaseService.java
> +    private static final String hibernate_show_sql = "true";
```suggestion
    private static final String HIBERNATE_SHOW_SQL = "true";
```

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/DataBaseService.java
> +
cs

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dao/AccountDAO.java
> +        Query query = session.createQuery("from User where login = :paramLogin");
```suggestion
        Query query = session.createQuery("SELECT FROM User WHERE login = :paramLogin");
```

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dataSets/User.java
> +    private static final long serialVersionUID = 1235469543;
do we need this field here?

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dataSets/User.java
> +    private long id;
better use wrapper

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dataSets/UsersDataSet.java
> +    private static final long serialVersionUID = -3581752392903938614L; // Serializable Important to Hibernate!
the same

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dataSets/UsersDataSet.java
> +    private long id;
wrapper

2019-07-12 08:22 UTC, Sofasmile commented on src/main/java/dbService/dataSets/UsersDataSet.java
> +}
add a blank line

2019-07-15 12:16 UTC, Sofasmile approved these changes

2019-07-15 12:16 UTC, Sofasmile commented on src/main/java/dbService/DataBaseService.java
> +    private static final String hibernate_hbm2ddl_auto = "update";
UPER_CASE

2019-08-19 13:04 UTC, closed without merging