Home work 27
UnitOmega13/HomeWork pull request #32
Opened 2019-07-21 19:24 UTC by UnitOmega13

2019-07-24 14:42 UTC, SevostyanovGerman requested changes

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/controller/MainPageServlet.java
> +    private boolean passwordCheck(String password, User user) {
del

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/controller/OrderConfirm.java
> +public class OrderConfirm extends HttpServlet {
cs

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/controller/OrderServlet.java
> +public class OrderServlet extends HttpServlet {
cs

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/controller/OrderServlet.java
> +            List<Optional<Product>> allProductInBasket = basketService.getUserBasket(user).get().getProducts();
Optional?

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/dao/BasketDAO.java
> +public interface BasketDAO {
cs

2019-07-24 14:42 UTC, SevostyanovGerman commented on src/src/main/java/dao/impl/BasketDAOImpl.java
> +public class BasketDAOImpl implements BasketDAO {
cs

2019-07-30 07:11 UTC, Sofasmile approved these changes

2019-08-19 13:29 UTC, closed without merging